name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose


  - pip:
    - numpy
    - scipy
    - scikit-learn
    - git+git://github.com/pl31/pgcontents.git
    - Babel
    - Flask
    - Jinja2==2.7.3
    - MarkupSafe==0.23
    - decorator==3.4.0
    - flipflop==1.0
    - psycopg2==2.5.4
    - pytz==2014.7
    - speaklater==1.3
